name: Code analysis

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  sonarcloud:
    name: SonarCloud Static code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
      - name: SonarQube Quality Gate check
        run: |
          sleep 5 # Give time for SonarCloud to process
          SONAR_STATUS=$(curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Ughanze23_Msc-Cloud-devOps-Project")
          if echo $SONAR_STATUS | grep -q '"status":"ERROR"'; then
            echo "SonarCloud Quality Gate failed"
            exit 1
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  securityanalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Run Bandit
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: |
          bandit -r ./website/ -f json -o bandit-report.json || echo "Issues found"
          # Check if serious vulnerabilities exist
          if [ "$(jq '.results | map(select(.issue_severity == "HIGH")) | length' bandit-report.json)" -gt 0 ]; then
            echo "High severity issues found in Bandit scan"
            exit 1
          fi

      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.json

      # Run Semgrep
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep for OWASP and Flask
        run: |
          semgrep --config "p/owasp-top-ten" --config "p/flask" --json --output semgrep-results.json ./website/ || echo "Issues found"
          # Check if serious vulnerabilities exist
          if [ "$(jq '.results | length' semgrep-results.json)" -gt 0 ]; then
            echo "Security issues found in Semgrep scan"
            exit 1
          fi

      - name: Upload Semgrep Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-results.json